spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  groovy:
    template:
      cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/cxyzj?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 15250823423wyX
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    properties:
      hibernate:
        ddl-auto: update
#        generate_statistics: true
        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    org.springframework:
      web: debug
      data: debug
    org:
      hibernate:
        stat: debug
    org.mybatis: debug
    com.dy.springboot.server.mapper: debug
    com.spring.jiminshiro.mapper: debug
server:
  port: 8080
